import styled from "@emotion/styled";
import Head from "next/head";
import React from "react";
import { LayoutProps } from "./Layout.interface";
import TopBar from "./TopBar.impl";

const Layout = ({ children }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>EosJS Exam</title>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <TopBar />
      </header>
      <main>{children}</main>
    </>
  );
};

export default Layout;
